### ISSUE TITLE
Ads API Depreciated API Exception

### ISSUE THREAD

**Issue by samhibberd** [digitalwithyou/craft-facebook-conversion#1]
I'm not sure if i'm missing something obvious, but running into a Depreciated API Exception when triggering any of the built in events?

> (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v10.0.

Just installed on `Craft CMS 3.6.7` and the facebook business api is installed at version `9.0.4`

Is there a setting in the facebook developer platform that we need to update?

**Comment by iamtompickering** [comment]
I have run into this same issue, running `Craft 3.4.27`.

Did you manage to resolve this @samhibberd ?

**Comment by samhibberd** [comment]
Not yet no @iamtompickering, looking at this again today, will let you know if I work anything out.

**Comment by Diewy** [comment]
Hi @samhibberd and @iamtompickering, it looks like Facebook updated there api version. I'm looking into it.

**Comment by Diewy** [comment]
Should be fixed in v1.0.3
