### ISSUE TITLE
cURL error when Facebook is down

### ISSUE THREAD

**Issue by bymayo** [digitalwithyou/craft-facebook-conversion#13]
One of our clients sites stopped working when Facebook went down today!

It would be good if there was a better exception for this, so if it returns a cURL error it doesn't break the whole site.

The error:

![CleanShot 2021-10-04 at 17 21 07](https://user-images.githubusercontent.com/522877/135887849-a8093e07-7160-4076-a33c-569db9e44db3.png)

**Comment by Diewy** [comment]
Sorry for the inconvenience, I've published a new version handling the error. It should be fixed in the latest version.

**Comment by bymayo** [comment]
Amazing, thanks for the VERY quick response and fix!
