### ISSUE TITLE
Deduplicated error

### ISSUE THREAD

**Issue by mattgeminiworktops** [digitalwithyou/craft-facebook-conversion#14]
I have set up as per your documentation and my Pixel is added by the SEOMatic plug in but I am seeing an error in Facebook as per below:

You're sending PageView events through both your pixel and the Conversions API, but they're not being deduplicated properly because not enough of these events are receiving an event_id parameter. Event instances sent without an event_id parameter cannot be deduplicated.

Add an event_id parameter to all PageView events that you're sending from both your pixel and the Conversions API. 

Any ideas how I can fix this?
Thanks

**Comment by toddprouty** [comment]
[This part of the readme](https://github.com/digitalwithyou/craft-facebook-conversion#template-implementation) may address your issue, specifically this bit:

> Please note, when the Facebook Pixel is already added by another plugin (E.g. SEOmatic) don't add the template hook to avoid duplication.

Or are you already excluding the template hook?

**Comment by cecilia-wsk** [comment]
I went to the same issue as @mattgeminiworktops (having already excluded the template hook) and I found out that if you add the event_id parameter (at same level as event_name) it works just fine. I left you a pull request with the small edits if you want to check it out.

**Comment by Diewy** [comment]
With the new v1.3 version you should be able to include an Event ID in the Twig function.
