### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by Punchprojects** [digitalwithyou/craft-facebook-conversion#17]
Hi,

Will there be a Craft 4 version soon?

Thanks

**Comment by jasondibenedetto** [comment]
Are there any updates on potentially getting this working for Craft 4?

**Comment by Diewy** [comment]
Hi @Punchprojects and @jasondibenedetto,

Should be ready next week!

**Comment by Diewy** [comment]
Check the newest version 🎉

**Comment by jasondibenedetto** [comment]
Thank you @Diewy, will check out this week.

**Comment by Punchprojects** [comment]
Thank you @Diewy!
