### ISSUE TITLE
Testing the server side conversion API

### ISSUE THREAD

**Issue by VdVChiel** [digitalwithyou/craft-facebook-conversion#2]
Is there a way we can test the inclusion API on the server? Facebook Business gives us a way to test this by adding a code to the test_event_code-parameter, but in the plugin no field is present to test this.

Is it possible to add a field or can we test this in any other way? 

Thanks in advance!

**Comment by Diewy** [comment]
Added support for the Test Codes!

**Comment by VdVChiel** [comment]
@Diewy Thank you.

I added the code but in FB business it is not being received as a server event. It tells me to 'Send the payload', does this happen automatically?

**Comment by Diewy** [comment]
Hi @VdVChiel, that should be included automatically yes.

A reason can be is that Facebook doesn't have any user data. If it's the first the time you visit the website directly (so not via a Facebook post/ad), Facebook doesn't have anything to link an account to the event. Facebook doesn't show any events that they can't link to a user.

Try doing a checkout, in which an emailadress in captured, that should be enough user data for Facebook to show the test event.

**Comment by VdVChiel** [comment]
@Diewy Thanks for the reply and the quick fix for the feature request!
