### ISSUE TITLE
Twig function to send any custom event

### ISSUE THREAD

**Issue by nikolenko-dmitriy** [digitalwithyou/craft-facebook-conversion#3]
It would be very useful to be able to send any custom conversion event from anywhere in the `twig templates` using some kind of function.

For example, I have to send an event about the `new lead` when the contact form was submitted and a `thank you message` was shown. Or probably send the conversion event when the user accesses some certain page on the website.

**Comment by Diewy** [comment]
Hi @nikolenko-dmitriy,

Very nice suggestion, thank you.

I've made a [first version](https://github.com/digitalwithyou/craft-facebook-conversion/commit/eb61638d68e43036c412f00854031ebc4dd78d84) in a separated branch. It would be used in a Twig template as follows:

```twig
{{ fbEvent('Purchase', {
    'email': 'jack@mail.com',
    'first_name': 'Jack',
    'last_name': 'Timberlake'
}, {
    'currency': 'EUR',
    'value': 20,
}) }}
```

Where the first parameter is the event name, second [user data](https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters), and third [custom data](https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/custom-data). Supporting all possibles keys.

Is this how you saw the implementation too?

**Comment by smith-john** [comment]
Hi @Diewy,

Yes, this solution would help a lot. Thanks!

**Comment by Diewy** [comment]
The Twig Function is now released. Also, [documentation](https://facebook-conversion.dwy.be/documentation/manual-tracking.html) was added to explain how to use it.

Thanks again for the suggestion!
