### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by sunscreem** [digitalwithyou/craft-facebook-conversion#31]
This plugin looks like exactly what my client needs. Can I check that it's GDPR compliant?  Ie. Website visitors can opt out of any tracking if needed?

**Comment by Diewy** [comment]
At this point all orders will be sent to Facebook, there is no way to opt-out. To be complient with the Cookie Law (or ePrivacy Directive) it is my understanding you'll need an opt-in, like accepting your privacy policy, but please check with your own legal contacts to see what is possible.

**Comment by sunscreem** [comment]
Thanks @Diewy
