### ISSUE TITLE
Event ID parameter

### ISSUE THREAD

**Issue by dellanesta** [digitalwithyou/craft-facebook-conversion#33]
Hi @Diewy we installed the plugin and configured the Meta pixel via Google Tag Mnaager. We pass server-side events using the twig function found in the documentation. however we fail to pass the "event id" of server side events and this prevents us from deduplicating events between Pixel and Conversion API. How can we fix? Looking at the code from the repository in the EventFunction class and subsequently in the sendEvent function there is no possibility to add the event_id.
Thank you, Michele

**Comment by Diewy** [comment]
Hi Michele,

Since this issue has been flagged before (#14, #15), I've added a new Event ID parameter in the Twig function.

**Comment by dellanesta** [comment]
Hi @Diewy perfect, thank you

**Comment by dellanesta** [comment]
hi @Diewy how can I track an event that should be called inside a javascript event like Click, scroll,...
