### ISSUE TITLE
Call Track inside javascript event

### ISSUE THREAD

**Issue by dellanesta** [digitalwithyou/craft-facebook-conversion#34]
hi @Diewy ,
how can I track an event that should be called inside a javascript event like Click, scroll,...

**Comment by Diewy** [comment]
Hi,

It works just the same as you would on any other project implementing the Facebook / Meta Pixel.

Just make sure you don't send the same event on both Client and Server side. E.g. The Purchase Event only on the server side.
Or, create a unique Event ID and send it with both Client and Server events.

Kind regards

**Comment by dellanesta** [comment]
hi @Diewy but i try to implement a custom event inside a click event and send the Server event immediatly and the client event correctly after the click... 

```
{% js%}
document.getElementById("testbutton").addEventListener("click", function() {
  //Client event      
  fbq('track', 'clickEvent', {  content_name: 'Click'},{eventID:'123456789' });
 
 //Server event
 {{ fbEvent('clickEvent',{},{'content_name': 'Click'},'123456789') }}
})
{% endjs %}
```
