### ISSUE TITLE
Removing external_id parameter?

### ISSUE THREAD

**Issue by iamtompickering** [digitalwithyou/craft-facebook-conversion#4]
The company managing our clients Facebook Pixel has said the following: 

```
step 1: Find the Conversion API. This code contains:
https://graph.facebook.com/
503486403326924 - Pixel ID
step 2: Find the param external_id and delete it
external_id is not required parameter
```

Does this make sense to you? Is this something you are able to change?

FB Pixels have always been a bit confusing to me, so I am not entirely sure what they are referring to here!

![IMG_4044](https://user-images.githubusercontent.com/6592882/116102378-933d9280-a6a6-11eb-92d0-163d45b18ba3.jpg)

**Comment by Diewy** [comment]
Hi @iamtompickering,

At first sight it looks like events are tracked twice, once by client and once by server. If that is the case, I would suggest only track the same events once. AddToCart and Purchase by server and Pageview by client.

See the first implementation in the [Facebook Documentation](https://developers.facebook.com/docs/marketing-api/conversions-api/deduplicate-pixel-and-server-events/).

Is that a solution that would work for you?

**Comment by Diewy** [comment]
Hi @iamtompickering, I'm going to close this for now. Let me know if you have any more questions.
