### ISSUE TITLE
Plugin causing Server errors in the CMS

### ISSUE THREAD

**Issue by iamtompickering** [digitalwithyou/craft-facebook-conversion#7]
I have just had to disable the plugin on a site because I was hitting server erorrs in the CMS when trying to search entries / products. 

Looking at the logs, I could see the following: 

```
Calling unknown method: craft\commerce\models\Address::getCountryIso() in /var/www/html/vendor/yiisoft/yii2/base/Component.php:301

The source seems to be
dwy\FacebookConversion\listeners\commerce\BaseCommerceEvent->getUserData
```

I expect the plugin has been updated with some new Commerce functions but you haven't included fallback code for older versions or something similar.

Please can you look into this for me?

**Comment by Diewy** [comment]
Hi @iamtompickering,

Thank you for notifying me about the issue, it should be fixed with the version that was released today.
