### ISSUE TITLE
Class 'craft\commerce\Plugin' not found

### ISSUE THREAD

**Issue by Grohon** [digitalwithyou/craft-facebook-conversion#8]
Getting the following error after updating the plugin. We do not have the Commerce plugin installed on the site.

`Error: Class 'craft\commerce\Plugin' not found in vendor/dwy/facebook-conversion/src/hooks/HeadTag.php:21`

**Comment by Diewy** [comment]
Hi @Grohon,

Thank you for reporting. The issue should be fixed.
